\cleardoublepage 

# (APPENDIX) Appendix {-}

# Writing Efficient Code

# Common Errors and debugging

RStudio is strongly recommended. Features -

-   matching pair of brackets
-   rainbow parenthesis

## single backslash in path

## Missing Quotes/brackets

## Creating list/vector of values using brackets only.

## Indexing starts with 1 (as against 0 in python)

## Package installation

## Sampling without seed

## Remember the difference between `=` and `==`

## Remember the differences between subsetting with `$` , `[` and `[[`

## Remember the functions may take individual vector or columns of data.frame

# Common Misconceptions

## Cross join vs many to many relationship

```{r}
tbl1 <- data.frame(
  stringsAsFactors = FALSE,
                 Head.Name = c("Salaries",
                               "Medical","Office Expenses","Salaries",
                               "Office Expenses","Office Expenses"),
   Budget.Provided = c(10000L, 5000L, 20000L, 9000L, 15000L, 5000L)
        )

tbl2 <- data.frame(
  stringsAsFactors = FALSE,
                 Head.Name = c("Salaries",
                               "Salaries","Medical","Office Expenses",
                               "Office Expenses","Salaries","Office Expenses",
                               "Office Expenses"),
                  Expenses = c(5000L,5000L,
                               4500L,10000L,9500L,9000L,15000L,5500L)
        )

library(tidyverse)
cross_join(tbl1, tbl2)

left_join(tbl1, tbl2,
          by = 'Head.Name') %>% 
  filter(Head.Name == 'Salaries')


```


use `with` or `%$%` pipe from magrittr

-   `$` operator is invalid for atomic vectors
-   `object of type ‘closure’ is not subsettable`

## Do not forget the implicit coercion

## `“subscript out of bounds” Error`

## `‘non-numeric argument to a binary operator’ Error`

# Quick Tips and Tricks

## add-ins datapasta

## Esquisse

## DataEditR
