--- 
title: "Data Analytics for audit using R"
author: "Anil Goyal"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This book is intended for auditors performing exploratory data analytics using R programming language, mainly baseR and Tidyverse."
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

# install the packages needed by this book; you fill out c(), e.g. c('ggplot2', 'dplyr')
lapply(c('xfun'), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})


options(tinytex.verbose = TRUE)


```

# Preface {-}

## Why R? {-}

## Preface {-}
Welcome to my book on R language, designed specifically for auditors who are interested in learning data analytics using open source resources. In today's digital age, data is abundant and ubiquitous, and its importance cannot be overstated. As a result, auditors must be equipped with the necessary skills to leverage this data and draw insights from it. This book is a result of my love for R and my passion for data analytics. In this book, I have tried to present R programming concepts and case studies that are useful in audit analysis as well as forensic audit and fraud investigation.

This book is written based on my notes on R while I was learning the language myself. I have included sufficient figures and examples to make the concepts easy to understand for readers with little or zero knowledge of programming.

R is an open-source programming language that has been gaining popularity in recent years due to its versatility and flexibility in data analysis. My journey with R began during Covid-19 lockdown, and I was introduced to R for data analysis by one of my colleagues. Since then, R has become an essential tool in my toolbox for data analysis.

One of the reasons why I fell in love with R is due to the well-laid concepts of Hadley Wickham. His contributions to the development of R programming concepts have made data analysis more accessible and efficient. The tidyverse, a collection of R packages developed by Wickham, has transformed the way data analysts and data scientists work with data. The tidyverse promotes a consistent and coherent way of working with data, making it easier to write code that is easier to read, understand, and maintain. Wickham's contributions to R have become the foundation of many data analysis tools in other programming languages, including pandas in Python and the DataFrames.jl package in Julia. I hope that this book will inspire readers to explore the vast potential of R and the contributions made by Wickham in data analytics.

One of the advantages of using free/open source tools like R is that they can be easily customized and extended to suit the specific needs of the user. Additionally, free/open source tools are often updated more frequently than licensed tools, ensuring that users have access to the latest features and bug fixes. Using licensed data analytics tools like Caseware IDEA, Tableau, and others can be expensive, and their licensing fees can be a significant burden on smaller organizations or individuals. By using open source tools like R, users can significantly reduce their costs while still having access to powerful data analytics capabilities.

Another strength of R is its extensive library of packages, which includes many tools for statistical analysis and data visualization. In this book, I have tried to make the concepts of R programming and data analytics as accessible as possible for auditors who may have little or zero knowledge of programming. The book is divided into two parts, the first part covers R programming concepts, and the second part covers case studies in forensic audit and fraud investigation using R.

I hope that this book will be a useful resource for auditors who want to learn data analytics using open source resources like R. I invite readers to share their suggestions and comments on the book to help me improve it further.

Happy reading and happy learning!

## Structure of the book {-}
This book is a comprehensive guide to learning the R programming language, from basic concepts to advanced topics. It is divided into three parts.

**Part One** covers basic programming concepts. **Chapter Zero** provides instructions for downloading and installing R, especially useful for first-time users of any programming language. **Chapter One** covers fundamental concepts, including data types and structures. Chapter Two explains how to subset R objects, such as vectors, matrices, and lists. **Chapter Three** covers pre-defined functions and operations in R, including conditions and logical operators, arithmetical and statistical functions, and string manipulation. **Chapter Four** includes how to use loops effectively for repetitive tasks, as well as defining custom functions. **Chapter Five** introduces the reader to functional programming, one of R's strengths, using the apply family of functions and the functions available in the purrr package. Finally, Chapter Six presents readers with an introduction to visualizations in R using `ggplot2`.

**Part Two** covers data analytics, with a focus on analyzing tabular data. **Chapter Seven** covers importing and exporting data in R. **Chapter Eight** provides techniques for data transformation using `dplyr`. **Chapter Nine** delves into techniques for joining tables for analysis, including relational but non-equi joins. **Chapter Ten** covers data wrangling using the `tidyr` package.

**Part Three** covers eight case studies, or use cases:

**Data Cleaning:** A critical step in the data analysis process, data cleaning involves identifying and correcting errors, inconsistencies, and missing values in the dataset. This chapter covers identifying and analysing duplicate records, unclean column names, etc. all using `janitor` package.

**Random Sampling in R:** This chapter covers several functions in R that generate random samples, including the `sample()` and `dplyr` functions.

**Benford's Law:** This statistical principle describes the frequency distribution of the first digit in many real-world datasets and is often used to detect fraudulent data or errors in data entry.

**Finding Duplicates:** Duplicates in a dataset can skew results and cause errors in data analysis. This chapter covers several methods for finding duplicates, using the R programming language.

**Detecting Gaps in Sequences:** When working with time series data, identifying gaps in the data is essential to avoid skewed results and incorrect conclusions. This chapter covers various methods for detecting gaps in sequential data.

**Merging Large Similar Datasets into One:** Usually the data is stored in excel files by auditee units, sometimes, separate files containing year-wise data or sometimes in multiple sheets and in multiple books.  This chapter covers several methods for merging two or more large datasets available in multiple sheets, books, files, etc. into a single, comprehensive dataset, using the R programming language.

**Sentiment Analysis through Word Clouds:** Sentiment analysis is a technique used to determine the sentiment or tone of a particular text or document. This chapter covers creating word clouds to visualize the results of sentiment analysis.

**Finding String Similarity:** String similarity is a measure of how similar two strings of text are, useful when working with large datasets containing text fields. This chapter covers several methods for finding string similarity, including the lexical similarity and phonetic similarity algorithms.

In addition to the main content of the book, there are two annexures that provide additional resources for readers. The **first annexure** covers file handling operations in R, including how to read and write files, work with directories, and perform basic file operations. The **second annexure** covers regular expressions in R, which are powerful tools for text processing and pattern matching. This annexure explains the syntax and usage of regular expressions in R, and provides examples of how to use them in practical situations. Together, these annexes provide readers with additional skills and knowledge that will enhance their ability to work with R and perform data analysis tasks.

## About author {-}
Anil Goyal is a data analytics enthusiast who has been working in the Indian Audit and Accounts Department since 1998. Currently posted in the Centre for Data Management and Analytics at the headquarters office in New Delhi, Anil has a passion for learning and applying programming languages/other tools such as R and Tableau to solve data-related challenges.

Anil is a self-taught expert in R, and has been involved in a variety of data analytics projects, including audits of the Public Financial Management System (PFMS), Pradhan Mantri Kisan Samman Nidhi, Pradhan Mantri Gramin Digital Saksharta Abhiyan (PMG-DISHA), and e-procurement through the Indian Railways eProcurement System.

Anil holds a post-graduate degree in Mathematics from the University of Rajasthan, Jaipur, which he received in 1998. This book is his first book. He continues to expand his skill set and knowledge in this field.

When not working with data, Anil enjoys pursuing his personal interests, which include bird photography, nature, and watching movies, etc..

## Acknowledgments {-}

A lot of people helped me when I was writing the book.

```{block2, type='flushright', html.tag='p'}
Anil Goyal
```


